spring:
    datasource:
        url: jdbc:mysql://localhost:3306/shop_c?serverTimezone=GMT%2B8
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    mail:
        host: smtp.qq.com
        protocol: smtp
        username: 891547988@qq.com
        password: tosxlkxufkupbcbe
        default-encoding: UTF-8
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true

mybatis:
    configuration:
        map-underscore-to-camel-case: true
    type-aliases-package: shop.demo.entity
    mapper-locations: classpath:mapper/*.xml

server:
    port: 8001
    servlet:
        context-path: /api